feat: add support for cors and integrate waku-frontend
waku-org/nwaku-compose pull request #30
Opened 2023-12-04 15:06 UTC by weboko

2023-12-04 15:06 UTC, weboko commented
@gabrielmer do we need to use custom nwaku image or latest to have the fix for cors?

2023-12-04 21:02 UTC, alrevuelta commented on run_node.sh
> +  --rest-allow-origin:"localhost:*"\
mm, is this flag an nwaku flag? can't find it.

2023-12-04 21:02 UTC, alrevuelta requested changes
thanks for the PR. left a comment.

2023-12-05 09:35 UTC, gabrielmer commented
> @gabrielmer do we need to use custom nwaku image or latest to have the fix for cors?

To have the fix for CORS we currently need the custom image `wakuorg/nwaku:debug-cors-wa` until fixes get merged to both nim-presto and nwaku.

If necessary I can create an image with a more meaningful/appropiate name

2023-12-05 09:43 UTC, gabrielmer commented on run_node.sh
> +  --rest-allow-origin:"localhost:*"\
This flag is going to be introduced and is not yet merged to master. We need to first merge a PR in nim-presto in order to create the PR in nwaku that would introduce this flag.

I built a custom image that includes the changes in nwaku and in nim-presto so we can use in the meantime, and in that image that flag is defined.

So if we want to use that flag, we need to also modify the image used by nwaku.

2023-12-05 19:58 UTC, weboko commented
This PR should be ready now.

2023-12-06 06:47 UTC, gabrielmer approved these changes
LGTM until we get the CORS fix into master. @alrevuelta what do you think?

2023-12-06 08:44 UTC, alrevuelta commented on docker-compose.yml
> +     - 127.0.0.1:8080:80
if the frontend listens on 3000, shouldnt this be
127.0.0.1:8080:3000


> Accepting connections at http://localhost:3000

2023-12-06 09:54 UTC, weboko commented on docker-compose.yml
> +     - 127.0.0.1:8080:80
It listens `8080`

2023-12-06 09:55 UTC, weboko commented
> I would prefer to wait until we have the cors issue fixed in a release, unless this blocks something else.

Fine by me, just to clarify - Chat is not working without it

2024-09-09 07:19 UTC, Ivansete-status commented
@weboko confirmed that we can close that one. Thanks for it :raised_hands: !

2024-09-09 07:19 UTC, closed without merging