feat: add caddy service
waku-org/nwaku-compose pull request #87
Opened 2024-04-25 05:51 UTC by kaichaosun

It enables,
- fix CORS options preflight request for nwaku
- free certificates for https

I don't have permission to push to this repo, could someone change this repo settings to allow `waku` team push changes?

2024-04-25 06:59 UTC, alrevuelta requested changes
Not sure I understand the intention behind this PR.

2024-04-25 06:59 UTC, alrevuelta commented on .gitignore
> -.env
why removing this?

2024-04-25 06:59 UTC, alrevuelta commented on README.md
> +Optionally, you can run it with caddy which gives a free SSL certificate for REST API,
do we need ssl certificates for this? frontend and waku node are supposed to run in the same machine. have the feeling this adds complexity to deployment and yet another service + stuff to configure. Note that nwaku-compose is supposed to be a tool for users to get a node up and running easily.

2024-04-25 06:59 UTC, alrevuelta commented on README.md
> +- change `your-domain.com` in `Caddyfile`
not sure i see value in having a custom domain. more things to configure that an average non tech savvy user might not want to do.

2024-04-25 07:04 UTC, kaichaosun commented on .gitignore
> -.env
It's duplicated above.

2024-04-25 07:11 UTC, kaichaosun commented on README.md
> +Optionally, you can run it with caddy which gives a free SSL certificate for REST API,
I misunderstood your intention, the way I want to proceed is, 
- having a generic way to setup a REST API (working for browser) which is provided by this PR.
- having different apps (waku-frontend, ferry-chat) connecting to the REST API by making it configurable in frontend.

Dockerize frontend apps here makes this repo complex, and the waku-frontend is not providing the stable features yet, ferry-chat is also super early and should not promoted to other self deployments.

2024-04-25 07:15 UTC, kaichaosun commented on README.md
> +- change `your-domain.com` in `Caddyfile`
Yeah, this is optional though, not too much harm to regular users.

2024-04-25 07:16 UTC, kaichaosun commented on README.md
> +Optionally, you can run it with caddy which gives a free SSL certificate for REST API,
More context here https://github.com/waku-org/nwaku/issues/2599

2024-04-25 08:07 UTC, alrevuelta commented on README.md
> +Optionally, you can run it with caddy which gives a free SSL certificate for REST API,
> Dockerize frontend apps here makes this repo complex

Yep, the idea is to dockerize it somewhere else, ferry-chat repo sounds like a good option. and then just use that image here in a new service.

> ferry-chat is also super early and should not promoted to other self deployments

sure, we can wait to integrate until its more mature. do we have a list with whats left? what I saw in https://ferry.chat seemed okay and rather simple but if you think there is a blocker we can wait.

2024-04-25 08:07 UTC, alrevuelta commented on README.md
> +- change `your-domain.com` in `Caddyfile`
nice, can we move it to `[ADVANCED.md](https://github.com/waku-org/nwaku-compose/blob/master/ADVANCED.md)` then?

2024-04-25 08:43 UTC, kaichaosun commented on README.md
> +Optionally, you can run it with caddy which gives a free SSL certificate for REST API,
If it's just a demo ui to show sending out messages and retrieve, current ferry-chat should be fine. 

There are remaining tasks to make it complete during implementing the chat-sdk features, which will bring a lot of broken changes to current ferry-chat, not sure how should we communicate with users who depend on it.
 https://miro.com/app/board/uXjVKQf-u5k=/?share_link_id=427152013190

2024-04-29 10:23 UTC, alrevuelta commented
Would like to block this until I understand wether we need this or not. @vpavlin any opinion?

2024-08-28 17:00 UTC, Ivansete-status commented
Thanks for that @kaichaosun !
What was its original purpose?

2024-08-29 01:29 UTC, kaichaosun commented
@Ivansete-status the changes use caddy as reverse proxy for nwaku REST API, so it can provides https service to frontend.
Not sure if it's still useful since waku frontend already integrate with the nwaku.

2024-08-30 13:44 UTC, Ivansete-status commented
> @Ivansete-status the changes use caddy as reverse proxy for nwaku REST API, so it can provides https service to frontend. Not sure if it's still useful since waku frontend already integrate with the nwaku.

Thanks Kaichao! In case we are not sure whether it is needed that may indicate is not needed :)

2024-08-30 14:43 UTC, closed without merging